
async function readFileAsBase64(file){const buf=await file.arrayBuffer();const b64=btoa(String.fromCharCode(...new Uint8Array(buf)));return b64;}
async function extractText(file){const base64=await readFileAsBase64(file);const res=await fetch('/api/extract-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,base64})});const data=await res.json();if(!res.ok)throw new Error(data.error||'extract failed');return data.text||'';}
async function generateQuestions(text,n,difficulty,apiKeyOpt){const headers={'Content-Type':'application/json'};if(apiKeyOpt)headers['x-api-key']=apiKeyOpt;const res=await fetch('/api/generate-questions',{method:'POST',headers,body:JSON.stringify({text, numQuestions:n, difficulty})});const data=await res.json();if(!res.ok)throw new Error(data.error||'generate failed');return data.questions;}
(function(){const sel=document.getElementById('themeSel');const apply=m=>{const r=document.documentElement;if(m==='light')r.classList.add('light');else r.classList.remove('light');localStorage.setItem('clp_theme',m)};const saved=localStorage.getItem('clp_theme')||'dark';if(sel)sel.value=saved;apply(saved);if(sel)sel.onchange=()=>apply(sel.value);
const apiKeyInp=document.getElementById('apiKey');const clearKey=document.getElementById('clearKey');const fileInput=document.getElementById('fileInput');const manualText=document.getElementById('manualText');const difficulty=document.getElementById('difficulty');const numQ=document.getElementById('numQ');const timeLimit=document.getElementById('timeLimit');const makeBtn=document.getElementById('makeBtn');const status=document.getElementById('status');
const quizCard=document.getElementById('quizCard');const questionZone=document.getElementById('questionZone');const quizTitle=document.getElementById('quizTitle');const nextBtn=document.getElementById('nextBtn');const skipBtn=document.getElementById('skipBtn');const finishBtn=document.getElementById('finishBtn');const feedback=document.getElementById('feedback');
let questions=[],idx=0,score=0,wrongTopics=[];
const k=localStorage.getItem('clp_openai');if(k){apiKeyInp.value='******** (שמורים מקומית)';}
clearKey.onclick=()=>{localStorage.removeItem('clp_openai');apiKeyInp.value='';};
makeBtn.onclick=async()=>{try{let key=apiKeyInp.value.trim();if(key.startsWith('sk-')){localStorage.setItem('clp_openai',key);}else{key=localStorage.getItem('clp_openai')||'';}status.textContent='מכין תוכן...';let text=manualText.value.trim();const f=fileInput.files[0];if(f){status.textContent='מחלץ טקסט מהקובץ...';const ext=f.name.toLowerCase().split('.').pop();if(ext==='txt'){text=(await f.text())+'\\n'+text;}else if(ext==='pdf'||ext==='docx'){text=(await extractText(f))+'\\n'+text;}else{alert('סוג קובץ לא נתמך: '+ext);return;}}if(!text||text.length<60){alert('נדרש טקסט בסיסי (לפחות כמה משפטים).');return;}status.textContent='יוצר שאלות בעזרת GPT‑4o...';questions=await generateQuestions(text.slice(0,40000),parseInt(numQ.value||'8',10),difficulty.value,key);if(!Array.isArray(questions)||!questions.length)throw new Error('לא התקבלו שאלות');idx=0;score=0;wrongTopics=[];quizCard.style.display='block';feedback.innerHTML='';renderQuestion();window.scrollTo({top:quizCard.offsetTop-20,behavior:'smooth'});status.textContent='';}catch(e){console.error(e);status.textContent='שגיאה: '+e.message;}};
function renderQuestion(){const q=questions[idx];quizTitle.textContent=`שאלה ${idx+1} מתוך ${questions.length}`;questionZone.innerHTML=`<div style="font-weight:800;margin-bottom:8px">${q.q}</div><div class="options">${q.options.map((opt,i)=>`<div class="option"><label><input type="radio" name="opt" value="${i}"> ${['א','ב','ג','ד'][i]}) ${opt}</label></div>`).join('')}</div>`;}
nextBtn.onclick=()=>{const sel=document.querySelector('input[name="opt"]:checked');if(!sel){alert('בחר/י תשובה');return;}const choice=parseInt(sel.value,10);const q=questions[idx];const ok=choice===q.answer;feedback.innerHTML=ok?`<div style="color:var(--ok);font-weight:700">✅ נכון</div><div>${q.explanation||''}</div>`:`<div style="color:var(--bad);font-weight:700">❌ לא נכון</div><div>תשובה נכונה: ${['א','ב','ג','ד'][q.answer]} — ${q.options[q.answer]}</div><div>${q.explanation||''}</div>`;if(ok)score++;else wrongTopics.push(q.topic||'כללי');setTimeout(()=>{idx++;feedback.innerHTML='';if(idx>=questions.length)finish();else renderQuestion();},900);};
skipBtn.onclick=()=>{idx++;if(idx>=questions.length)finish();else{feedback.innerHTML='';renderQuestion();}};
finishBtn.onclick=finish;
function finish(){const payload={score,total:questions.length,wrongTopics,questions};localStorage.setItem('clp_results',JSON.stringify(payload));window.location.href='./results.html';}
})();